[build]
  command = "composer install && php artisan key:generate && php artisan migrate && php artisan storage:link && php artisan serve --port=$PORT --host=0.0.0.0"
  publish = "public"

[dev]
  command = "composer install && php artisan serve --port=$PORT --host=0.0.0.0"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
